default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: live_chat_development

test:
  <<: *default
  database: live_chat_test

production:
  <<: *default
  database: live_chat_production
  username: live_chat
  password: <%= ENV["LIVE_CHAT_DATABASE_PASSWORD"] %>
